/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    int a = 2;
    int b = 3;
    int x = 1;
    int y = 10;
    System.out.println(new App().getGreeting());
    Calculate calc = new Calculate();
    System.out.println("Sum of " + a + " and " + b + " is " + calc.sum(a, b) + ".Average is "
        + calc.ave(calc.sum(a, b), calc.count(a, b)) + ".");
    System.out.println("Sum of " + x + " to " + y + " is " + calc.total(x, y) + ".Average is "
        + calc.ave(calc.total(x, y), calc.count(x, y)) + ".");
    System.out.println(
        "Sum of odd of " + x + " to " + y + " is " + calc.odd(x, y) + ".Sum of even is " + calc.even(x, y) + ".");
  }
}
